export const LOADING_START_G = 'LOADING_START_G'
export const LOADING_END_G = 'LOADING_END_G'
export const FETCH_GALLERY_SUCCESS = 'FETCH_GALLERY_SUCCESS'
export const FETCH_GALLERY_ERROR = 'FETCH_GALLERY_ERROR'
